# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/pavan-ambekar/Bytecode "

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/pavan-ambekar/Bytecode /build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/pavan-ambekar/Bytecode /build/CMakeFiles" "/home/pavan-ambekar/Bytecode /build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/pavan-ambekar/Bytecode /build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bytecode

# Build rule for target.
Bytecode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bytecode
.PHONY : Bytecode

# fast build rule for target.
Bytecode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/build
.PHONY : Bytecode/fast

src/bytecode.o: src/bytecode.cpp.o
.PHONY : src/bytecode.o

# target to build an object file
src/bytecode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/bytecode.cpp.o
.PHONY : src/bytecode.cpp.o

src/bytecode.i: src/bytecode.cpp.i
.PHONY : src/bytecode.i

# target to preprocess a source file
src/bytecode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/bytecode.cpp.i
.PHONY : src/bytecode.cpp.i

src/bytecode.s: src/bytecode.cpp.s
.PHONY : src/bytecode.s

# target to generate assembly for a file
src/bytecode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/bytecode.cpp.s
.PHONY : src/bytecode.cpp.s

src/compiler.o: src/compiler.cpp.o
.PHONY : src/compiler.o

# target to build an object file
src/compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/compiler.cpp.o
.PHONY : src/compiler.cpp.o

src/compiler.i: src/compiler.cpp.i
.PHONY : src/compiler.i

# target to preprocess a source file
src/compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/compiler.cpp.i
.PHONY : src/compiler.cpp.i

src/compiler.s: src/compiler.cpp.s
.PHONY : src/compiler.s

# target to generate assembly for a file
src/compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/compiler.cpp.s
.PHONY : src/compiler.cpp.s

src/lexer.o: src/lexer.cpp.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/vm.o: src/vm.cpp.o
.PHONY : src/vm.o

# target to build an object file
src/vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/vm.cpp.o
.PHONY : src/vm.cpp.o

src/vm.i: src/vm.cpp.i
.PHONY : src/vm.i

# target to preprocess a source file
src/vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/vm.cpp.i
.PHONY : src/vm.cpp.i

src/vm.s: src/vm.cpp.s
.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bytecode.dir/build.make CMakeFiles/Bytecode.dir/src/vm.cpp.s
.PHONY : src/vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bytecode"
	@echo "... src/bytecode.o"
	@echo "... src/bytecode.i"
	@echo "... src/bytecode.s"
	@echo "... src/compiler.o"
	@echo "... src/compiler.i"
	@echo "... src/compiler.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/vm.o"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

